name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## 🚀 Algorithm Visualizer ${{ github.ref_name }}
          
          ### 🚀 How to Run
          
          **Requirements**: Python 3.8 or higher
          
          ```bash
          # Download source code
          git clone https://github.com/Rblea97/Algorithm-Visualizer.git
          cd Algorithm-Visualizer
          
          # Run the application
          python main.py
          ```
          
          ### ✨ What's New
          Interactive sorting algorithm visualizer featuring:
          - **5 sorting algorithms** with step-by-step visualization
          - **Real-time controls** and speed adjustment  
          - **Educational content** with complexity information
          - **Professional three-panel interface**
          
          ### 🎯 Perfect For
          - Computer science students learning algorithms
          - Educators teaching sorting concepts
          - Algorithm visualization and comparison
          - Interview preparation and technical demonstrations